language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1

install:
  - php -d memory_limit=-1  $(which composer) instal

script:
  - ./vendor/bin/check_code_style.sh
  - ./vendor/bin/phpunit
